### ISSUE TITLE
Running userscript-proxy at the network level (without manually adding proxy)

### ISSUE THREAD

**Issue by amanadhav-shopify** [SimonAlling/userscript-proxy#5]
I have written my own ad blocker and auto-translation Greasemonkey script that I like to run in my browser at home. However, I would like to run this script for my whole network at home without needing to manually connect to the proxy every time. Can I just add the proxy to my router settings? Is this possible? If so how? (A bit new to networking forgive my lack of terminology)

**Comment by SimonAlling** [comment]
I think [the `--transparent` flag](https://github.com/SimonAlling/userscript-proxy#--transparent--t) might be what you're looking for. You'd set it like this:

```bash
docker run -t --rm --name userscript-proxy -p 8080:8080 alling/userscript-proxy --transparent
#          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                         ^^^^^^^^^^^^^
#          flags to `docker run`                                                flags to Userscript Proxy
```

I've only used transparent mode in a VPN setup (#4) though, so I don't really know how the network should be configured in your scenario. I'd suggest reading [mitmproxy's documentation on transparent mode](https://docs.mitmproxy.org/stable/concepts-modes/#transparent-proxy). :slightly_smiling_face:

**Comment by SimonAlling** [comment]
Any success yet, @amanadhav-shopify?

An alternative solution might be [PAC + WPAD](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol) (in which case I think you should _not_ use `--transparent`).

**Comment by SimonAlling** [comment]
I'm closing this issue for now. Feel free to reopen it if needed.
